ekf_filter_node:
  ros__parameters:
    debug: true  # Добавьте в ekf.yaml
    use_sim_time: true
    publish_tf: true
    frequency: 50.0
    # Задержка перед очисткой буфера (сек)
    #tf_timeout: 1.5  
    # Игнорировать небольшие скачки времени
    #tf_time_jump_threshold: 0.05  
    #sensor_timeout: 0.1
    two_d_mode: true
    
        #x     , y     , z,
        #roll  , pitch , yaw,
        #vx    , vy    , vz,
        #vroll , vpitch, vyaw,
        #ax    , ay    , az

    # Источник 1: Колёсная одометрия
    odom0: diff_cont/odom     # Топик одометрии
    odom0_config: [true, true, false,
                  false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false, false, false]

    #odom0_pose_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 7.75]  # x, y, z, roll, pitch, yaw
    #odom0_twist_covariance_diagonal: [0.05, 0.05, 0.05, 0.1, 0.1, 0.05]  # vx, vy, vz, vroll, vpitch, vyaw

    # Источник 2: IMU
    imu0: /imu        # Топик IMU
    imu0_config: [false, false, false,
                  false,  false,  true,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
                  
    #imu0_pose_covariance_diagonal: [0.1, 0.1, 0.1, 0.5, 0.5, 0.1] 
    #imu0_twist_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    odom0_differential: true  
    imu0_differential: true   

    # Фреймы
    map_frame: map 
    odom_frame: odom
    base_link_frame: root_link
    world_frame: map

    odom0_pose_rejection_threshold: 10.0 
        
    odom0_queue_size: 1
    odom0_nodelay: false
    odom0_remove_gravitational_acceleration: false
    odom0_relative: false

    imu0_pose_rejection_threshold: 1.0
    imu0_queue_size: 1
    imu0_nodelay: false
    imu0_relative: false