slam_toolbox:
  ros__parameters:
    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: root_link
    scan_topic: /scan
    mode: mapping
    debug_logging: false

    # Частота обновлений
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 1.0
    minimum_time_interval: 0.1

    # Параметры сканирования
    resolution: 0.05
    min_laser_range: 0.1
    max_laser_range: 20.0
    scan_buffer_size: 20

    # Фильтрация движений
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2

    # Отключение коррекции одометрии
    use_scan_matching: false
    do_loop_closing: false
    use_scan_barycenter: false

    # Прочие параметры
    async: true
    tf_buffer_duration: 10.0