controller_manager:
  ros__parameters:
    update_rate: 50              # частота обновления контроллеров

    # регистрируем контроллеры
    diff_cont:
      type: diff_drive_controller/DiffDriveController
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

# ----------------- DiffDriveController -----------------
diff_cont:
  ros__parameters: 
    odom_frame_id: odom
    base_frame_id: root_link
    enable_odom_tf: false
    publish_odom_tf: false
    left_wheel_names: 
      - "base_to_left_forward_wheel"
      - "base_to_left_middle_wheel"
      - "base_to_left_rear_wheel"
    right_wheel_names: 
      - "base_to_right_forward_wheel"
      - "base_to_right_middle_wheel"
      - "base_to_right_rear_wheel"
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
      - position
    wheel_separation: 0.9
    wheel_radius: 0.23
    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    state_publish_rate: 50.0 # Defaults to 50