controller_manager:
  ros__parameters:
    update_rate: 50              # частота обновления контроллеров

    # регистрируем контроллеры
    diff_cont:
      type: diff_drive_controller/DiffDriveController
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

# ----------------- DiffDriveController -----------------
diff_cont:
  ros__parameters: 
    left_wheel_names: 
      - "base_to_l_f_wheel"
      - "base_to_l_m_wheel"
      - "base_to_l_r_wheel"
    right_wheel_names: 
      - "base_to_r_f_wheel"
      - "base_to_r_m_wheel"
      - "base_to_r_r_wheel"
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
    wheel_separation: 0.8
    wheel_radius: 0.19
    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    state_publish_rate: 50.0 # Defaults to 50
