/**:
odom_fusion:
  ros__parameters:
    odom_topic: "/diff_cont/odom"  # Топик одометрии
    imu_topic: "/imu/data"              # Топик IMU
    output_topic: "/odom"          # Выходной топик
    child_frame: "root_link"       # Дочерний фрейм (обычно base_link)
    world_frame: "odom"            # Мировой фрейм
    publish_tf: true               # Публиковать TF?
    min_speed: 0.001                # Минимальная скорость для фильтрации
    min_angular_speed: 0.025