teleop_node:
  ros__parameters:
    enable_button: 4             # Кнопка включения телепорта (измените при необходимости)
    enable_turbo_button: 5       # Кнопка турбо режима (измените при необходимости)
    axis_linear:
      x: 1                       # Ось для линейного движения
    scale_linear:
      x: 0.4                     # Масштаб линейной скорости
      turbo: 0.8                 # Масштаб линейной скорости в турбо режиме
    axis_angular:
      yaw: 3                     # Ось для углового движения
    scale_angular:
      yaw: 0.4                   # Масштаб угловой скорости
      turbo: 0.5                 # Масштаб угловой скорости в турбо режиме
    deadzone: 0.05               # Мертвая зона джойстика