teleop_node:
  ros__parameters:
    enable_button: 0             # Кнопка включения телепорта (измените при необходимости)
    enable_turbo_button: 1       # Кнопка турбо режима (измените при необходимости)
    axis_linear:
      x: 1                       # Ось для линейного движения (обычно 1 для левого стика по вертикали)
    scale_linear:
      x: 0.7                     # Масштаб линейной скорости
      turbo: 1.5                 # Масштаб линейной скорости в турбо режиме
    axis_angular:
      yaw: 0                     # Ось для углового движения (обычно 0 для левого стика по горизонтали)
    scale_angular:
      yaw: 0.4                   # Масштаб угловой скорости
      turbo: 1.0                 # Масштаб угловой скорости в турбо режиме
    deadzone: 0.05               # Мертвая зона джойстика